const http2=require('http2'),fs=require('fs'),WebSocket=require('ultimate-ws')
const token="",TARGET_GUILD="",GATEWAY="wss://gateway-us-east1-b.discord.gg/?v=9&encoding=json"
const guilds={};let mfa=null,session=null,seq=null,resuming=false,heartbeatTimer=null
const pool=[],POOL_SIZE=1000000000000000000000
function createConnection(){const c=http2.connect('https://canary.discord.com',{peerMaxConcurrentStreams:100,settings:{enablePush:false}});c.on('error',()=>{});c.on('goaway',()=>{const i=pool.indexOf(c);if(i!==-1){pool.splice(i,1);try{c.close()}catch{}}setTimeout(()=>pool.push(createConnection()),800+Math.random()*400)});return c}
for(let i=0;i<POOL_SIZE;i++)pool.push(createConnection())
function getConn(){for(const c of pool)if(!c.destroyed&&!c.closed)return c;const n=createConnection();pool.push(n);return n}
function claim(code){var body=JSON.stringify({code:code}),h={":method":"PATCH",":path":"/api/v9/guilds/"+TARGET_GUILD+"/vanity-url","content-type":"application/json","content-length":Buffer.byteLength(body),"authorization":token,"user-agent":"Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0","x-super-properties":"eyJicm93c2VyIjoiRmlyZWZveCIsImJyb3dzZXJfdXNlcl9hZ2VudCI6IkZpcmVmb3gifQ=="};if(mfa)h["x-discord-mfa-authorization"]=mfa;for(var i=0;i<POOL_SIZE;i++){;(function(idx){setTimeout(function(){var c=getConn();try{var r=c.request(h);r.on('response',function(hd){var d='';r.on('data',function(ch){d+=ch});r.on('end',function(){if(hd[':status']===200)console.log('[OK] '+code);else console.log('['+hd[':status']+'] '+code)})});r.on('error',function(){});r.end(body)}catch(e){}},idx*(50+Math.floor(Math.random()*30)))})(i)}}
function connect(){var ws=new WebSocket(GATEWAY);ws.on('open',function(){if(resuming&&session){ws.send(JSON.stringify({op:6,d:{token:token,session_id:session,seq:seq}}))}else{ws.send(JSON.stringify({op:2,d:{token:token,intents:1,properties:{os:'Linux',browser:'Firefox',device:''},compress:false,large_threshold:50}}))}});ws.on('message',function(raw){var msg;try{msg=JSON.parse(raw)}catch(e){return}var t=msg.t,op=msg.op,d=msg.d,s=msg.s;if(s)seq=s;if(op===10){var interval=d.heartbeat_interval;if(heartbeatTimer)clearInterval(heartbeatTimer);setTimeout(function(){try{ws.send(JSON.stringify({op:1,d:seq}))}catch(e){}},Math.floor(interval*Math.random()));heartbeatTimer=setInterval(function(){try{ws.send(JSON.stringify({op:1,d:seq}))}catch(e){}},interval);return}if(op===11)return;if(op===9){resuming=!!d;if(heartbeatTimer){clearInterval(heartbeatTimer);heartbeatTimer=null}setTimeout(function(){try{ws.close()}catch(e){}connect()},2e3+Math.random()*3e3);return}if(op===7){resuming=true;if(heartbeatTimer){clearInterval(heartbeatTimer);heartbeatTimer=null}try{ws.close()}catch(e){}setTimeout(function(){connect()},300+Math.random()*200);return}if(t==='READY'){session=d.session_id;resuming=false;var count=0;if(d.guilds){for(var i=0;i<d.guilds.length;i++){var g=d.guilds[i];if(g.vanity_url_code){guilds[g.id]=g.vanity_url_code;count++}}}console.log('ready, '+count+' tracked')}if(t==='RESUMED')resuming=false;if(t==='GUILD_CREATE'){if(d&&d.id&&d.vanity_url_code)guilds[d.id]=d.vanity_url_code}if(t==='GUILD_UPDATE'){if(!d||!d.id)return;var old=guilds[d.id],now=d.vanity_url_code;if(old&&old!==now){console.log(old+' -> '+(now||'none'));claim(old)}if(now)guilds[d.id]=now;else delete guilds[d.id]}if(t==='GUILD_DELETE'){if(d&&d.id&&guilds[d.id]){var v=guilds[d.id];console.log(v+' lost');claim(v);delete guilds[d.id]}}});ws.on('close',function(){if(heartbeatTimer){clearInterval(heartbeatTimer);heartbeatTimer=null}if(!resuming)resuming=true;setTimeout(function(){connect()},1500+Math.random()*1e3)});ws.on('error',function(){setTimeout(function(){connect()},2e3+Math.random()*1e3)})}
function watchMfa(){var update=function(){try{var val=fs.readFileSync("mfa.txt").toString().trim();mfa=val||null}catch(e){mfa=null}};update();fs.watchFile("mfa.txt",{interval:3e3},update)}
setInterval(function(){for(var i=pool.length-1;i>=0;i--){if(pool[i].destroyed||pool[i].closed){pool.splice(i,1);setTimeout(function(){pool.push(createConnection())},500+Math.random()*500)}}},7e3)
watchMfa();setTimeout(function(){connect()},500)
